server:
  host: 0.0.0.0
  port: 8090
  read_timeout: 10s
  write_timeout: 10s

cors:
  allow_origins: https://appbox.xdarren.com

provider:
  default: tinytext
  stellar:
    enabled: true
    name: stellar
    base_url: http://stellar:8000/api/v1
    gateway_header: X-Gateway-Key
    gateway_key: d810ea4beed31ef9feddd3562baef08c58039dac7680392dafb9a929632f0137
    timeout: 10s
  tinytext:
    enabled: true
    name: tinytext
    base_url: https://tinytext.xdarren.com/api/v1
    gateway_header: X-Gateway-Key
    gateway_key: 9998ae434a760ff2a885c1166d8ecf6558055adb31e95bd8b367edea58f8cf35
    timeout: 10s
